version: "3.9"
services:

  backend:
    image: "backend:${BACK_VER}"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${BACK_PORT}:5000"
    environment:
      - "SECRET_KEY=${BACK_SECRET_KEY}"
      - "SQLALCHEMY_DATABASE_URI=${BACK_SQLALCHEMY_DATABASE_URI}"
      - "BACK_FLASK_DEBUG=${BACK_FLASK_DEBUG}"
      - "SERVER_NAME=${BACK_SERVER_NAME}"
    depends_on:
      - database

  database:
    image: "postgres:${POSTGRES_IMAGE_VER}"
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"

  superviser: #A supprimer
    image: "adminer:latest"
    ports:
      - "8080:8080"
    environment:
      - "ADMINER_DEFAULT_SERVER=database"
      - "ADMINER_DESIGN=pepa-linha"